services:
  wordpress:
    image: wordpress:latest
    container_name: wp
    volumes:
      - ../src/:/var/www/html
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME:
    restart: no
    networks:
      - net-wordpress

networks:
  net-wordpress:
    external: true
