services:
  db:
    image: mysql:latest
    container_name: wp-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: no
    networks:
      - net-wordpress

networks:
  net-wordpress:
    external: true

volumes:
  db_data: {}
